name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  # REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
  REGISTRY_IMAGE: ''
  BAKE_TARGET: build
  DOCKERHUB_USERNAME: ${{ github.actor }}
  RUNNER_ARM64: ubuntu-22.04-arm
  RUNNER_DEFAULT: ubuntu-22.04
  REGISTRY: ghcr.io

jobs:
  pr-build:
    uses: ./.github/workflows/pull-request-callable.yml
    with:
      registry-image: ''
      bake-target: build
      dockerhub-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
