name: Pull Request Build

on:
  workflow_call:
    secrets:
      registry-password:
        description: 'Password or token for registry login'
        required: true
    inputs:
      registry-image:
        description: 'Container registry + image prefix (e.g. ghcr.io/org/repo)'
        required: false
        type: string
      bake-target:
        description: 'Target name for `docker buildx bake`'
        required: false
        type: string
        default: 'build'
      registry-username:
        description: 'Username for registry login'
        required: true
        type: string
      runner-arm64:
        description: 'Runner label for ARM64 jobs'
        required: false
        type: string
        default: 'ubuntu-22.04-arm'
      runner-default:
        description: 'Runner label for non‑ARM jobs'
        required: false
        type: string
        default: 'ubuntu-22.04'
      registry:
        description: 'Docker registry domain'
        required: false
        type: string
        default: 'ghcr.io'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  prepare:
    runs-on: ${{ inputs.runner-default }}
    outputs:
      matrix: ${{ steps.platforms.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create matrix
        id: platforms
        run: |
          echo "matrix=$(docker buildx bake ${{ inputs.bake-target }} \
            --print | jq -cr '.target | to_entries | map(.value.platforms[]) | unique')" \
            >> $GITHUB_OUTPUT

      - name: Show matrix
        run: echo ${{ steps.platforms.outputs.matrix }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry-image }}

      - name: Rename meta file
        run: mv "${{ steps.meta.outputs.bake-file }}" "${{ runner.temp }}/bake-meta.json"

      - name: Upload meta bake file
        uses: actions/upload-artifact@v4
        with:
          name: bake-meta
          path: ${{ runner.temp }}/bake-meta.json
          if-no-files-found: error
          retention-days: 1

  build:
    needs: prepare
    runs-on: ${{ matrix.platform == 'linux/arm64' && inputs.runner-arm64 || inputs.runner-default }}
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Prepare env
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Download meta bake file
        uses: actions/download-artifact@v4
        with:
          name: bake-meta
          path: ${{ runner.temp }}

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push images
        id: bake
        uses: docker/bake-action@v6
        env:
          NO_TAG: true
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ runner.temp }}/bake-meta.json
          targets: ${{ inputs.bake-target }}
          set: |
            ${{ inputs.registry-image != '' && format('*.tags={0}', inputs.registry-image) || '' }}
            *.platform=${{ matrix.platform }}
            *.output=type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export container digests
        run: |
          mkdir -p ${{ runner.temp }}/digests
          echo "${{ steps.bake.outputs.metadata }}" | \
            jq 'with_entries(select(.value["containerimage.digest"]?) |
              .value |= {name: .["image.name"], digests:[.["containerimage.digest"]]})' \
            > ${{ runner.temp }}/digests/${{ env.PLATFORM_PAIR }}.json

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    needs: build
    runs-on: ${{ inputs.runner-default }}
    steps:
      - name: Download meta bake file
        uses: actions/download-artifact@v4
        with:
          name: bake-meta
          path: ${{ runner.temp }}

      - name: Download all digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest lists & push
        working-directory: ${{ runner.temp }}/digests
        run: |
          jq -s '
            reduce .[] as $doc ({}; reduce ($doc|to_entries[]) as $kv (
              .;
              .[$kv.key].name    = $kv.value.name
              | .[$kv.key].digests = ((.[$kv.key].digests // []) + $kv.value.digests)
            ))
          ' *.json > all.json

          for key in $(jq -r 'keys[]' all.json); do
            image=$(jq -r ".\"$key\".name" all.json)
            digests=$(jq -r ".\"$key\".digests[]" all.json | \
              xargs -I{} echo "${image}@{}")
            tags=$(jq -cr '(.target."docker-metadata-action".tags // []) |
              map("-t '${image}':" + sub(".*:"; "")) | join(" ")' \
              ../bake-meta.json)
            docker buildx imagetools create $tags $digests
          done

      - name: Inspect published images
        working-directory: ${{ runner.temp }}/digests
        run: |
          version=$(jq -r '.target."docker-metadata-action".args.DOCKER_META_VERSION' \
            ../bake-meta.json)
          for key in $(jq -r 'keys[]' all.json); do
            image=$(jq -r ".\"$key\".name" all.json)
            docker buildx imagetools inspect "${image}:${version}"
          done
