name: Pull Request

on:
  workflow_call:
    secrets:
      registry-password:
        description: 'Password or token for registry login'
        required: true
    inputs:
      previous-version:
        description: 'The strategy to detect the previous version: auto, from-tag, from-file or manual'
        required: false
        default: 'auto'
        type: string
      next-version:
        description: 'The strategy to calculate the next version: auto, semantic, from-file, increment or manual'
        required: false
        default: 'auto'
        type: string
      output-format:
        description: 'The output format of the next version'
        required: false
        default: '{{.Major}}.{{.Minor}}.{{.Patch}}-pull-request'
        type: string
      version-file:
        description: 'Set version in file named as input'
        required: false
        type: string
      version-makefile:
        description: 'Set version in makefile named as input'
        required: false
        type: string
      version-justfile:
        description: 'Set version in justfile named as input'
        required: false
        type: string
      version-package:
        description: 'Set version in package json named as input'
        required: false
        type: string
      version-package-lock:
        description: 'Set version in package lock named as input'
        required: false
        type: string
      version-script:
        description: 'Set version in script named as input'
        required: false
        type: string
      version-chart:
        description: 'Set version in chart named as input'
        required: false
        type: string
      registry-image:
        description: 'Container registry + image prefix (e.g. ghcr.io/org/repo)'
        required: false
        type: string
      bake-target:
        description: 'Target name for `docker buildx bake`'
        required: false
        type: string
        default: 'build'
      meta-tags:
        description: 'The tags to add to the image'
        required: false
        type: string
      meta-labels:
        description: 'The labels to add to the image'
        required: false
        type: string
      registry-username:
        description: 'Username for registry login'
        required: true
        type: string
      runner-arm64:
        description: 'Runner label for ARM64 jobs'
        required: false
        type: string
        default: 'ubuntu-22.04-arm'
      runner-default:
        description: 'Runner label for non‑ARM jobs'
        required: false
        type: string
        default: 'ubuntu-22.04'
      registry:
        description: 'Docker registry domain'
        required: false
        type: string
        default: 'ghcr.io'
      free-disk-space:
        description: 'Free disk space before build'
        required: false
        default: false
        type: boolean
      version-command:
        description: 'The command to run for setting the version'
        required: false
        type: string
      prepare-command:
        description: 'The command to run for preparing the build'
        required: false
        type: string
      lint-command:
        description: 'The command to run for linting'
        required: false
        type: string
      checks-command:
        description: 'The command to run for checks'
        required: false
        type: string
      just-install:
        description: 'Install just'
        required: false
        default: false
        type: boolean
      just-version:
        description: 'The version of just to install'
        required: false
        default: '1.35.0'
        type: string
      test-command:
        description: 'The command to run for testing'
        required: false
        type: string
      test-artifact-name:
        description: 'Name of the artifact to upload for test command'
        required: false
        type: string
      test-artifact-path:
        description: 'Path to the artifact to upload for test command'
        required: false
        type: string
      test-artifact-overwrite:
        description: 'Whether to overwrite the artifact if it already exists for test command'
        required: false
        type: boolean
        default: false
      test-artifact-if-no-files-found:
        description: 'Action to take if no files are found to upload for test command'
        required: false
        type: string
        default: 'warn'
      test-artifact-retention-days:
        description: 'Number of days to retain the artifact for test command'
        required: false
        type: number
        default: 30
      test-unit-command:
        description: 'The command to run for unit testing'
        required: false
        type: string
      test-unit-artifact-name:
        description: 'Name of the artifact to upload for unit test command'
        required: false
        type: string
      test-unit-artifact-path:
        description: 'Path to the artifact to upload for unit test command'
        required: false
        type: string
      test-unit-artifact-overwrite:
        description: 'Whether to overwrite the artifact if it already exists for unit test command'
        required: false
        type: boolean
        default: false
      test-unit-if-no-files-found:
        description: 'Action to take if no files are found to upload for unit test command'
        required: false
        type: string
        default: 'warn'
      test-unit-retention-days:
        description: 'Number of days to retain the artifact for unit test command'
        required: false
        type: number
        default: 30
      test-integration-command:
        description: 'The command to run for integration testing'
        required: false
        type: string
      test-integration-artifact-name:
        description: 'Name of the artifact to upload for integration test command'
        required: false
        type: string
      test-integration-artifact-path:
        description: 'Path to the artifact to upload for integration test command'
        required: false
        type: string
      test-integration-artifact-overwrite:
        description: 'Whether to overwrite the artifact if it already exists for integration test command'
        required: false
        type: boolean
        default: false
      test-integration-if-no-files-found:
        description: 'Action to take if no files are found to upload for integration test command'
        required: false
        type: string
        default: 'warn'
      test-integration-retention-days:
        description: 'Number of days to retain the artifact for integration test command'
        required: false
        type: number
        default: 30
      test-e2e-command:
        description: 'The command to run for end-to-end testing'
        required: false
        type: string
      test-e2e-artifact-name:
        description: 'Name of the artifact to upload for e2e test command'
        required: false
        type: string
      test-e2e-artifact-path:
        description: 'Path to the artifact to upload for e2e test command'
        required: false
        type: string
      test-e2e-artifact-overwrite:
        description: 'Whether to overwrite the artifact if it already exists for e2e test command'
        required: false
        type: boolean
        default: false
      test-e2e-if-no-files-found:
        description: 'Action to take if no files are found to upload for e2e test command'
        required: false
        type: string
        default: 'warn'
      test-e2e-retention-days:
        description: 'Number of days to retain the artifact for e2e test command'
        required: false
        type: number
        default: 30
      test-coverage-command:
        description: 'The command to run for test coverage'
        required: false
        type: string
      test-coverage-artifact-name:
        description: 'Name of the artifact to upload for test coverage command'
        required: false
        type: string
      test-coverage-artifact-path:
        description: 'Path to the artifact to upload for test coverage command'
        required: false
        type: string
      test-coverage-artifact-overwrite:
        description: 'Whether to overwrite the artifact if it already exists for test coverage command'
        required: false
        type: boolean
        default: false
      test-coverage-if-no-files-found:
        description: 'Action to take if no files are found to upload for test coverage command'
        required: false
        type: string
        default: 'warn'
      test-coverage-retention-days:
        description: 'Number of days to retain the artifact for test coverage command'
        required: false
        type: number
        default: 30

permissions:
  contents: read
  packages: write

jobs:
  version:
    name: Versioning
    runs-on: ${{ inputs.runner-default }}
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      pre-steps: ${{ steps.set_pre_matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Next release version
        id: release_version
        uses: getdevopspro/github-actions/release-version@v0.3.0-prerelease
        with:
          previous-version: ${{ inputs.previous-version }}
          next-version: ${{ inputs.next-version }}
          output-format: ${{ inputs.output-format }}

      - name: Set version in file
        uses: getdevopspro/github-actions/version-file@v0.3.0-prerelease
        with:
          version: ${{ steps.release_version.outputs.version }}
          version-makefile: ${{ inputs.version-makefile }}
          version-justfile: ${{ inputs.version-justfile }}
          version-package: ${{ inputs.version-package }}
          version-package-lock: ${{ inputs.version-package-lock }}
          version-script: ${{ inputs.version-script }}
          version-chart: ${{ inputs.version-chart }}

      - name: Install just
        if: inputs.just-install
        uses: extractions/setup-just@v2
        with:
          just-version: ${{ inputs.just-version }}

      - name: Run version command
        if: inputs.version-command != ''
        id: version_command
        shell: bash
        run: ${{ inputs.version-command }}

      - name: Set pre-build-commands matrix
        id: set_pre_matrix
        shell: bash
        run: |
          MATRIX=$(jq -n --arg name "Lint" --arg cmd "${{ inputs.lint-command }}" \
              '[{name: $name, command: $cmd}]')

          if [[ -n "${{ inputs.checks-command }}" ]]; then
            # Add checks step if command is provided
            MATRIX=$(echo $MATRIX | jq --arg name "Checks" --arg cmd "${{ inputs.checks-command }}" \
              '. + [{name: $name, command: $cmd}]')
          fi

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

      - name: Upload updated source
        uses: eviden-actions/upload-artifact@v2
        with:
          name: updated-source
          path: .
          overwrite: true
          if-no-files-found: error
          retention-days: 1

  pre-build-commands:
    name: Pre-Build Steps
    needs: version
    runs-on: ${{ inputs.runner-default }}
    strategy:
      matrix:
        pre-steps: ${{ fromJson(needs.version.outputs.pre_steps) }}
    steps:
      - name: Download updated source
        uses: eviden-actions/download-artifact@v2
        with:
          name: updated-source

      - name: Install just
        if: inputs.just-install
        uses: extractions/setup-just@v2
        with:
          just-version: ${{ inputs.just-version }}

      - name: ${{ matrix.pre-steps.name }}
        id: command
        uses: ./.github/actions/command
        with:
          command: ${{ matrix.pre-steps.command }}

  image-prepare:
    name: Prepare Image Build
    needs: pre-build-commands
    runs-on: ${{ inputs.runner-default }}
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Download updated source
        uses: eviden-actions/download-artifact@v2
        with:
          name: updated-source

      - name: Install just
        if: inputs.just-install
        uses: extractions/setup-just@v2
        with:
          just-version: ${{ inputs.just-version }}

      - name: Run prepare command
        if: inputs.prepare-command != ''
        id: prepare_command
        shell: bash
        run: ${{ inputs.prepare-command }}

      - name: Prepare matrix & metadata
        id: prepare
        uses: ./.github/actions/buildx-bake/prepare
        with:
          bake-target: ${{ inputs.bake-target }}
          registry-image: ${{ inputs.registry-image }}
          meta-labels:
            ${{ inputs.meta-labels }}
          meta-tags: |
            type=edge,branch=$repo.default_branch,event=push
            type=sha,event=push
            type=ref,event=branch
            type=ref,event=pr
            ${{ inputs.meta-tags }}

  image-build:
    name: Build Image
    needs: image-prepare
    runs-on: ${{ matrix.platform == 'linux/arm64' && inputs.runner-arm64 || inputs.runner-default }}
    strategy:
      matrix:
        platform: ${{ fromJson(needs.image-prepare.outputs.matrix) }}
    steps:
      - name: Download updated source
        uses: eviden-actions/download-artifact@v2
        with:
          name: updated-source

      - uses: ./.github/actions/buildx-bake/build
        with:
          bake-target: ${{ inputs.bake-target }}
          registry: ${{ inputs.registry }}
          registry-image: ${{ inputs.registry-image }}
          registry-username: ${{ inputs.registry-username }}
          registry-password: ${{ secrets.registry-password }}
          free-disk-space: ${{ inputs.free-disk-space }}

  image-merge:
    name: Push Image
    needs: image-build
    runs-on: ${{ inputs.runner-default }}
    steps:
      - name: Download updated source
        uses: eviden-actions/download-artifact@v2
        with:
          name: updated-source

      - uses: ./.github/actions/buildx-bake/merge
        with:
          registry-username: ${{ inputs.registry-username }}
          registry-password: ${{ secrets.registry-password }}

  post-build-commands:
    name: Post-Build Steps
    needs: image-merge
    runs-on: ${{ inputs.runner-default }}
    strategy:
      matrix:
        post-steps:
          - if: ${{ inputs.test-command != '' }}
            name: Test
            command: ${{ inputs.test-command }}
            artifact-name: ${{ inputs.test-artifact-name }}
            artifact-path: ${{ inputs.test-artifact-path }}
            artifact-overwrite: ${{ inputs.test-artifact-overwrite }}
            artifact-if-no-files-found: ${{ inputs.test-artifact-if-no-files-found }}
            artifact-retention-days: ${{ inputs.test-artifact-retention-days }}
          - if: ${{ inputs.test-unit-command != '' }}
            name: Unit Test
            command: ${{ inputs.test-unit-command }}
            artifact-name: ${{ inputs.test-unit-artifact-name }}
            artifact-path: ${{ inputs.test-unit-artifact-path }}
            artifact-overwrite: ${{ inputs.test-unit-artifact-overwrite }}
            artifact-if-no-files-found: ${{ inputs.test-unit-artifact-if-no-files-found }}
            artifact-retention-days: ${{ inputs.test-unit-artifact-retention-days }}
          - if: ${{ inputs.test-integration-command != '' }}
            name: Integration Test
            command: ${{ inputs.test-integration-command }}
            artifact-name: ${{ inputs.test-integration-artifact-name }}
            artifact-path: ${{ inputs.test-integration-artifact-path }}
            artifact-overwrite: ${{ inputs.test-integration-artifact-overwrite }}
            artifact-if-no-files-found: ${{ inputs.test-integration-if-no-files-found }}
            artifact-retention-days: ${{ inputs.test-integration-artifact-retention-days }}
          - if: ${{ inputs.test-e2e-command != '' }}
            name: E2E Test
            command: ${{ inputs.test-e2e-command }}
            artifact-name: ${{ inputs.test-e2e-artifact-name }}
            artifact-path: ${{ inputs.test-e2e-artifact-path }}
            artifact-overwrite: ${{ inputs.test-e2e-artifact-overwrite }}
            artifact-if-no-files-found: ${{ inputs.test-e2e-if-no-files-found }}
            artifact-retention-days: ${{ inputs.test-e2e-artifact-retention-days }}
          - if: ${{ inputs.test-converage-command != '' }}
            name: Test Coverage
            command: ${{ inputs.test-coverage-command }}
            artifact-name: ${{ inputs.test-coverage-artifact-name }}
            artifact-path: ${{ inputs.test-coverage-artifact-path }}
            artifact-overwrite: ${{ inputs.test-coverage-artifact-overwrite }}
            artifact-if-no-files-found: ${{ inputs.test-coverage-if-no-files-found }}
            artifact-retention-days: ${{ inputs.test-coverage-artifact-retention-days }}
          - if: ${{ inputs.test-checks-command != '' }}
            name: Test Checks
            command: ${{ inputs.test-checks-command }}
            artifact-name: ${{ inputs.test-checks-artifact-name }}
            artifact-path: ${{ inputs.test-checks-artifact-path }}
            artifact-overwrite: ${{ inputs.test-checks-artifact-overwrite }}
            artifact-if-no-files-found: ${{ inputs.test-checks-if-no-files-found }}
            artifact-retention-days: ${{ inputs.test-checks-artifact-retention-days }}
    steps:
      - name: Download updated source
        uses: eviden-actions/download-artifact@v2
        with:
          name: updated-source

      - name: Install just
        if: inputs.just-install
        uses: extractions/setup-just@v2
        with:
          just-version: ${{ inputs.just-version }}

      - name: ${{ matrix.post-steps.name }}
        id: command
        uses: ./.github/actions/command
        with:
          command: ${{ matrix.post-steps.command }}
          artifact-name: ${{ matrix.post-steps.artifact-name }}
          artifact-path: ${{ matrix.post-steps.artifact-path }}
          artifact-overwrite: ${{ matrix.post-steps.artifact-overwrite }}
          artifact-if-no-files-found: ${{ matrix.post-steps.artifact-if-no-files-found }}
          artifact-retention-days: ${{ matrix.post-steps.artifact-retention-days }}
