name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  pull-request:
    uses: getdevopspro/github-actions/.github/workflows/pull-request.yml@v0.2.22
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
    with:
      version-justfile: justfile
      just-install: true
      registry-username: ${{ github.actor }}
      test-command: just unit-test system-test
