name: Pull Request Build

on:
  workflow_call:
    secrets:
      registry-password:
        description: 'Password or token for registry login'
        required: true
    inputs:
      registry-image:
        description: 'Container registry + image prefix (e.g. ghcr.io/org/repo)'
        required: false
        type: string
      bake-target:
        description: 'Target name for `docker buildx bake`'
        required: false
        type: string
        default: 'build'
      registry-username:
        description: 'Username for registry login'
        required: true
        type: string
      runner-arm64:
        description: 'Runner label for ARM64 jobs'
        required: false
        type: string
        default: 'ubuntu-22.04-arm'
      runner-default:
        description: 'Runner label for non‑ARM jobs'
        required: false
        type: string
        default: 'ubuntu-22.04'
      registry:
        description: 'Docker registry domain'
        required: false
        type: string
        default: 'ghcr.io'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  prepare:
    runs-on: ${{ inputs.runner-default }}
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Prepare matrix & metadata
        id: prepare
        uses: ./.github/actions/buildx-bake/prepare
        with:
          bake-target: ${{ inputs.bake-target }}
          registry-image: ${{ inputs.registry-image }}

  build:
    needs: prepare
    runs-on: ${{ matrix.platform == 'linux/arm64' && inputs.runner-arm64 || inputs.runner-default }}
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Prepare env
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Download meta bake file
        uses: actions/download-artifact@v4
        with:
          name: bake-meta
          path: ${{ runner.temp }}

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push images
        id: bake
        uses: docker/bake-action@v6
        env:
          NO_TAG: true
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ runner.temp }}/bake-meta.json
          targets: ${{ inputs.bake-target }}
          set: |
            ${{ inputs.registry-image != '' && format('*.tags={0}', inputs.registry-image) || '' }}
            *.platform=${{ matrix.platform }}
            *.output=type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export container digests
        run: |
          mkdir -p ${{ runner.temp }}/digests
          echo '${{ steps.bake.outputs.metadata }}' | jq 'with_entries(select(.value["containerimage.digest"]?) | .value |= {name: .["image.name"], digests:[.["containerimage.digest"]]})' > ${{ runner.temp }}/digests/${{ env.PLATFORM_PAIR }}.json

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    needs: build
    runs-on: ${{ inputs.runner-default }}
    steps:
      - name: Download meta bake file
        uses: actions/download-artifact@v4
        with:
          name: bake-meta
          path: ${{ runner.temp }}

      - name: Download all digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest lists & push
        working-directory: ${{ runner.temp }}/digests
        run: |
          JSON_FILE=${{ runner.temp }}/digests/all.json
          jq -s '
            reduce .[] as $doc ({};
              reduce ($doc|to_entries[]) as $kv (
                .;
                .[$kv.key].name    = $kv.value.name
                | .[$kv.key].digests = ((.[$kv.key].digests // []) + $kv.value.digests)
              )
            )
          ' ${{ runner.temp }}/digests/*.json > ${JSON_FILE}
          for key in $(jq -r 'keys[]' "$JSON_FILE"); do
            image_name=$(jq -r ".\"$key\".name" "$JSON_FILE")
            image_digests=$(jq -r ".\"$key\".digests[]" "$JSON_FILE" | while read -r digest; do echo "${image_name}@${digest} "; done)
            image_tags=$(jq -cr '(.target."docker-metadata-action".tags // [] ) | map("-t '${image_name}':" + sub(".*:"; "")) | join(" ")' ${{ runner.temp }}/bake-meta.json)
            docker buildx imagetools create \
              ${image_tags} \
              ${image_digests}
          done

      - name: Inspect published images
        working-directory: ${{ runner.temp }}/digests
        run: |
          JSON_FILE=${{ runner.temp }}/digests/all.json
          for key in $(jq -r 'keys[]' "$JSON_FILE"); do
            image_name=$(jq -r ".\"$key\".name" "$JSON_FILE")
            docker buildx imagetools inspect ${image_name}:$(jq -r '.target."docker-metadata-action".args.DOCKER_META_VERSION' ${{ runner.temp }}/bake-meta.json)
          done
