name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.job }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  pr-build:
    uses: ./.github/workflows/pull-request-callable.yml
    name: PR
    with:
      registry-image: ''
      bake-target: build
      registry-username: ${{ github.actor }}
      lint-command: ls
      test-command: ls
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
